[package]
name = "leoscript-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leoscript-lib = { path = "../leoscript-lib" }
clap = { version = "4.4.11", features = ["derive"] }
